# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fdbc6576bc12281f52d0b2287cba70ee9e7a23f7391224b85d681a6a8377a480a799f436f0311360dbdd100182f5eb503cc2dae8fc69c653e80e0a4fc16d1741

test:
  secret_key_base: 85ad6bc4fc9c23136f1da4e9ac1ea34c24bc6cb771c9f26749f7460e3868987ef9bff0257240637fbf50124818ae6de1f54b45596b404199fe29407718211b59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
